/* Generated by Yosys 0.9 (git sha1 1979e0b) */
/*

=== q1 ===

   Number of wires:                 10
   Number of wire bits:             24
   Number of public wires:           2
   Number of public wire bits:      16
   Number of memories:               0
   Number of memory bits:            0
   Number of processes:              0
   Number of cells:                 15
     $_OR_                           8
     $_XOR_                          7

*/
(* top =  1  *)
(* src = "q1.sv:1" *)
module syq1(a, w);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "q1.sv:1" *)
  input [7:0] a;
  (* src = "q1.sv:1" *)
  output [7:0] w;
  assign w[1] = a[1] ^ a[0];
  assign _00_ = a[1] | a[0];
  assign w[2] = _00_ ^ a[2];
  assign _01_ = _00_ | a[2];
  assign w[3] = _01_ ^ a[3];
  assign _02_ = a[3] | a[2];
  assign _03_ = _02_ | _00_;
  assign w[4] = _03_ ^ a[4];
  assign _04_ = _03_ | a[4];
  assign w[5] = _04_ ^ a[5];
  assign _05_ = a[5] | a[4];
  assign _06_ = _05_ | _03_;
  assign w[6] = _06_ ^ a[6];
  assign _07_ = _06_ | a[6];
  assign w[7] = _07_ ^ a[7];
  assign w[0] = a[0];
endmodule
