/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "q2_a.sv:1" *)
module q2_a(a, b, ci, sum, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "q2_a.sv:1" *)
  input a;
  (* src = "q2_a.sv:1" *)
  input b;
  (* src = "q2_a.sv:1" *)
  input ci;
  (* src = "q2_a.sv:1" *)
  output co;
  (* src = "q2_a.sv:1" *)
  output sum;
  NOT _10_ (
    .A(b),
    .Y(_06_)
  );
  NOR _11_ (
    .A(a),
    .B(ci),
    .Y(_07_)
  );
  NOT _12_ (
    .A(_07_),
    .Y(_08_)
  );
  NAND _13_ (
    .A(a),
    .B(ci),
    .Y(_09_)
  );
  NOT _14_ (
    .A(_09_),
    .Y(_00_)
  );
  NOR _15_ (
    .A(_07_),
    .B(_00_),
    .Y(_01_)
  );
  NAND _16_ (
    .A(_08_),
    .B(_09_),
    .Y(_02_)
  );
  NOR _17_ (
    .A(_06_),
    .B(_02_),
    .Y(_03_)
  );
  NAND _18_ (
    .A(b),
    .B(_01_),
    .Y(_04_)
  );
  NOR _19_ (
    .A(b),
    .B(_01_),
    .Y(_05_)
  );
  NOR _20_ (
    .A(_03_),
    .B(_05_),
    .Y(sum)
  );
  NAND _21_ (
    .A(_09_),
    .B(_04_),
    .Y(co)
  );
endmodule
