/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "moore_without_default.v:1" *)
module moor_without_default(clk, rst, j, w);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "moore_without_default.v:1" *)
  input clk;
  (* src = "moore_without_default.v:1" *)
  input j;
  (* onehot = 32'd1 *)
  wire [4:0] ps;
  (* src = "moore_without_default.v:1" *)
  input rst;
  (* src = "moore_without_default.v:1" *)
  output w;
  NOT _14_ (
    .A(j),
    .Y(_05_)
  );
  NOT _15_ (
    .A(ps[1]),
    .Y(_06_)
  );
  NOT _16_ (
    .A(ps[3]),
    .Y(_07_)
  );
  NAND _17_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  NOR _18_ (
    .A(ps[0]),
    .B(_08_),
    .Y(_09_)
  );
  NOR _19_ (
    .A(_05_),
    .B(_09_),
    .Y(_03_)
  );
  NOR _20_ (
    .A(ps[0]),
    .B(ps[2]),
    .Y(_10_)
  );
  NOR _21_ (
    .A(j),
    .B(_10_),
    .Y(_00_)
  );
  NOR _22_ (
    .A(ps[4]),
    .B(_08_),
    .Y(_11_)
  );
  NOR _23_ (
    .A(j),
    .B(_11_),
    .Y(_02_)
  );
  NAND _24_ (
    .A(j),
    .B(ps[2]),
    .Y(_12_)
  );
  NOT _25_ (
    .A(_12_),
    .Y(_04_)
  );
  NAND _26_ (
    .A(j),
    .B(ps[4]),
    .Y(_13_)
  );
  NOT _27_ (
    .A(_13_),
    .Y(_01_)
  );
  DFF_PP1 _28_ (
    .C(clk),
    .D(_00_),
    .Q(ps[0]),
    .R(rst)
  );
  DFF_PP0 _29_ (
    .C(clk),
    .D(_01_),
    .Q(ps[1]),
    .R(rst)
  );
  DFF_PP0 _30_ (
    .C(clk),
    .D(_02_),
    .Q(ps[2]),
    .R(rst)
  );
  DFF_PP0 _31_ (
    .C(clk),
    .D(_03_),
    .Q(ps[3]),
    .R(rst)
  );
  DFF_PP0 _32_ (
    .C(clk),
    .D(_04_),
    .Q(ps[4]),
    .R(rst)
  );
  assign w = ps[1];
endmodule
